"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { LogOut, Sparkles } from "lucide-react";
import { FEATURE_DEFINITIONS, getEnabledNavigation } from "@/lib/constants";
import { GlassCard } from "@/components/shared/GlassCard";
import { LoadingSkeleton } from "@/components/shared/LoadingSkeleton";
import { NeonButton } from "@/components/shared/NeonButton";
import { StatusBadge } from "@/components/shared/StatusBadge";

type AppFeature = {
  featureKey: keyof typeof FEATURE_DEFINITIONS;
  name: string;
  description: string;
  route: string;
  enabled: boolean;
};

type AppMe = {
  user: {
    name: string;
    email: string;
    role: string;
    tenant: { name: string; slug: string; plan: string; status: string } | null;
  };
};

export function UserDashboardPlaceholder() {
  const [features, setFeatures] = useState<AppFeature[]>([]);
  const [me, setMe] = useState<AppMe["user"] | null>(null);
  const [loading, setLoading] = useState(true);
  const enabledNavigation = getEnabledNavigation(features);

  useEffect(() => {
    Promise.all([
      fetch("/api/app/me", { credentials: "include", cache: "no-store" }),
      fetch("/api/app/features", { credentials: "include", cache: "no-store" })
    ])
      .then(async ([meResponse, featureResponse]) => {
        if (!meResponse.ok || !featureResponse.ok) throw new Error("Workspace access blocked");
        const meData = (await meResponse.json()) as AppMe;
        const featureData = (await featureResponse.json()) as { features: AppFeature[] };
        setMe(meData.user);
        setFeatures(featureData.features ?? []);
      })
      .finally(() => setLoading(false));
  }, []);

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST", credentials: "include" });
    window.location.href = "/login";
  }

  return (
    <main className="min-h-screen bg-[#030712] text-white">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_18%_18%,rgba(34,211,238,0.16),transparent_30rem),radial-gradient(circle_at_82%_12%,rgba(37,99,235,0.13),transparent_32rem)]" />
      <div className="relative z-10 mx-auto flex min-h-screen max-w-7xl flex-col px-4 py-6 sm:px-6 lg:px-8">
        <header className="flex flex-wrap items-center justify-between gap-4 rounded-[28px] border border-white/10 bg-white/[0.035] p-4 backdrop-blur-2xl">
          <div className="flex items-center gap-3">
            <span className="grid h-11 w-11 place-items-center rounded-2xl border border-cyan-300/30 bg-cyan-300/10 text-cyan-100 shadow-glow">
              <Sparkles className="h-5 w-5" />
            </span>
            <div>
              <p className="font-semibold">{me?.tenant?.name ?? "Company Workspace"}</p>
              <p className="text-xs text-slate-500">Feature-controlled user panel foundation</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            {me?.tenant ? <StatusBadge value={me.tenant.plan} /> : null}
            <NeonButton size="sm" variant="secondary" onClick={logout}>
              <LogOut className="h-4 w-4" />
              Logout
            </NeonButton>
          </div>
        </header>

        <section className="grid flex-1 items-center gap-8 py-10 lg:grid-cols-[0.9fr_1.1fr]">
          <div>
            <p className="text-sm uppercase tracking-[0.28em] text-cyan-200/80">Workspace</p>
            <h1 className="mt-4 max-w-3xl text-4xl font-semibold leading-tight md:text-6xl">
              Your workspace is ready.
            </h1>
            <p className="mt-5 max-w-2xl text-base leading-7 text-slate-400">
              Full user panel will be built next. For now, this page reads enabled features from the backend and only shows
              modules the platform admin has switched on for your company.
            </p>
            <div className="mt-6 flex flex-wrap gap-3 text-sm text-slate-300">
              <span className="rounded-full border border-white/10 bg-white/[0.04] px-4 py-2">{me?.name ?? "User"}</span>
              <span className="rounded-full border border-white/10 bg-white/[0.04] px-4 py-2">{me?.role?.replaceAll("_", " ")}</span>
              <span className="rounded-full border border-white/10 bg-white/[0.04] px-4 py-2">{me?.tenant?.status ?? "ACTIVE"}</span>
            </div>
          </div>

          <GlassCard className="p-5">
            <h2 className="text-xl font-semibold text-white">Enabled navigation</h2>
            <p className="mt-2 text-sm leading-6 text-slate-400">
              These tiles are generated by <span className="font-mono text-cyan-100">getEnabledNavigation(features)</span>.
            </p>
            {loading ? (
              <div className="mt-5"><LoadingSkeleton rows={4} /></div>
            ) : (
              <div className="mt-5 grid gap-3 sm:grid-cols-2">
                {enabledNavigation.map((item) => {
                  const definition = FEATURE_DEFINITIONS[item.featureKey];
                  return (
                    <Link
                      key={item.featureKey}
                      href={item.href}
                      className="rounded-[22px] border border-white/10 bg-white/[0.04] p-4 transition hover:-translate-y-1 hover:border-cyan-300/30 hover:bg-cyan-300/10"
                    >
                      <p className="font-semibold text-white">{definition.navLabel}</p>
                      <p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-400">{definition.description}</p>
                    </Link>
                  );
                })}
              </div>
            )}
          </GlassCard>
        </section>
      </div>
    </main>
  );
}
